{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "memcached.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "memcached.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "memcached.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "memcached.serviceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
