{{- if include "memcached.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "memcached.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "memcached.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.username }}
  username: {{ .Values.auth.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.password }}
  password: {{ .Values.auth.password | b64enc | quote }}
  {{- end }}
{{- end }}
